captcha-milestone-v1
Garrafao/phitag pull request #86
Opened 2024-02-12 09:31 UTC by sachinn12

2024-02-19 08:43 UTC, AinaIanemahy approved these changes

2024-02-19 08:46 UTC, AinaIanemahy reviewed
Partial Review Database Changes

2024-02-28 12:37 UTC, AinaIanemahy requested changes
I have left some comments. Please have a look at them. I think that there are some classes that are quite large that might contain duplicate code structures or might be refactored in the long run. Also there is some phitag-prod related stuff again.

2024-02-28 12:37 UTC, AinaIanemahy commented on backend/src/main/java/de/garrafao/phitag/application/common/OrdinalDistanceFunctionWithDoubles.java
> +                if (v != null) {
Feel like you could refactor this a bit

2024-02-28 12:37 UTC, AinaIanemahy commented on backend/src/main/java/de/garrafao/phitag/application/instance/InstanceApplicationService.java
This class is really long. Maybe you could split it?

2024-02-28 12:37 UTC, AinaIanemahy commented on backend/src/main/java/de/garrafao/phitag/computationalannotator/common/function/CommonFunction.java
CommonFunction is not an ideal name.

2024-02-28 12:37 UTC, AinaIanemahy commented on frontend/lib/BackendRoutes.ts
Maybe remove phitag here?

2024-02-28 12:37 UTC, AinaIanemahy commented on frontend/pages/_app.tsx
Remove these changes. Phitag prod.

2024-02-28 12:37 UTC, AinaIanemahy commented on frontend/pages/about-us.tsx
Should be phitag prod

2024-02-28 12:37 UTC, AinaIanemahy commented on frontend/pages/register.tsx
Check for all instances of font-uni-corporate-bold and change them back.

2024-02-29 08:23 UTC, sachinn12 commented on backend/src/main/java/de/garrafao/phitag/application/common/OrdinalDistanceFunctionWithDoubles.java
> +                if (v != null) {
I noted this will be fixed in next push

2024-02-29 08:23 UTC, sachinn12 commented on backend/src/main/java/de/garrafao/phitag/computationalannotator/common/function/CommonFunction.java
will be fixed in next push by next week

2024-02-29 08:24 UTC, sachinn12 commented on frontend/pages/register.tsx
done

2024-02-29 08:25 UTC, sachinn12 commented on backend/src/main/java/de/garrafao/phitag/application/instance/InstanceApplicationService.java
will do in next push

2024-02-29 08:56 UTC, AinaIanemahy approved these changes

2024-02-29 10:00 UTC, AinaIanemahy approved these changes

2024-02-29 10:00 UTC, merged